package parser;

public enum TokenType {
	COMMENT_BLOCK, COMMENT_LINE,NEWLINE, WHITESPACE,
    BEGIN, END, INT, BOOL, IF, THEN, ELSE, DO, WHILE, FOR, PRINT,
    GT, GTE, EQ, PLUS, MULT, ASSIGN, SEMI, COMMA, LPAREN, RPAREN, LBRACE, RBRACE,
    BOOL_LITERAL, Id, Num, UNKNOWN, EOF
}
